{{- range .Values.services}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  labels:
    app: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      name: {{.name}}
      labels:
        app: {{.name}}
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      hostname: {{.name}}
      containers:
        - name: {{.name}}
          image: {{.image}}
          livenessProbe:
            httpGet:
              port: {{.port}}
              path: {{.alt_liveliness | default "/actuator/health/liveness"}}
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: {{.port}}
              path: "/actuator/health/readiness"
            initialDelaySeconds: 15
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: {{.name}}
spec:
  selector:
    app: {{.name}}
  ports:
    - protocol: TCP
      port: {{.port}}
      targetPort: {{.port}}
  type: NodePort

---
{{- end}}