opentelemetry-collector-daemonset:
  mode: daemonset
  presets:
    kubeletMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodAnnotations: true
      extractAllPodLabels: true
  config:
    receivers:
      kubeletstats:
        collection_interval: 10s
        insecure_skip_verify: true

    exporters:
      otlp:
        endpoint: "http://otel-collector:4317"
        tls:
          insecure: true
      # for debugging
      logging:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200

    service:
      pipelines:
        metrics:
          receivers: [ kubeletstats ]
          processors: [ k8sattributes ]
          exporters: [ logging, otlp ]

opentelemetry-collector-deployment:
  mode: deployment
  presets:
    hostMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodAnnotations: true
      extractAllPodLabels: true
  config:
    exporters:
      otlp:
        endpoint: "http://otel-collector:4317"
        tls:
          insecure: true
      # for debugging
      logging:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200

    service:
      pipelines:
        metrics:
          receivers: [ hostmetrics ]
          processors: [ k8sattributes ]
          exporters: [ logging, otlp ]
